#ifndef BF_CONFIG_H
#define BF_CONFIG_H


/*
    all defines refer to the index of the packet
*/
#define DESTINATION_ADDRESS_INDEX 16
#define ETHERNET_DESTINATION_ADDRESS_SIZE 12
#define SOURCE_ADDRESS_INDEX 28
#define ETHERNET_SOURCE_ADDRESS_SIZE 12
#define ETHERNET_TYPE_INDEX 40
#define ETHERNET_TYPE_SIZE 4
#define ETHERNET_PAYLOAD_INDEX 44
#define ETHERNET_CRC_SiZE 8
//FIXME: convert them to array indices
// #define ECPRI_BF_VERSION_INDEX 44
// #define ECPRI_BF_VERSION_SIZE 1
// #define ECPRI_CONCATENATION_INDICATOR_INDEX 45
// #define ECPRI_CONCATENATION_INDICATOR_SIZE 1

// #define ECPRI_PAYLOAD_SIZE_INDEX 0
// #define ECPRI_MESSAGE_TYPE_INDEX 2
// #define ECPRI_CONCATENATION_INDICATOR_INDEX 3
// #define ECPRI_RTC_ID_INDEX 4
// #define ECPRI_SEQUENCE_ID_INDEX 8
// #define ECPRI_PAYLOAD_INDEX 10
// #define ECPRI_PAYLOAD_SIZE 20
// #define ECPRI_MESSAGE_TYPE 2
// #define ECPRI_CONCATENATION_INDICATOR 0
// #define ECPI_RTC_ID 8068
// #define ECPRI_SEQUENCE_ID 384


#endif //BF_CONFIG_H