#ifndef ECF_CONFIG_H
#define ECF_CONFIG_H

#define PROTOCOL_REVISION_INDEX 44
#define PROTOCOL_REVISION_SIZE 1
#define CONCATENATION_INDICATOR_BYTE_INDEX 45
#define CONCATENATION_INDICATOR_BYTE_SIZE 1
#define CONCATENATION_INDICATOR_BIT_INDEX 3
#define MESSAGE_TYPE_INDEX 46
#define MESSAGE_TYPE_SIZE 2
#define PAYLOAD_SIZE_INDEX 48
#define PAYLOAD_SIZE_SIZE 4
#define RTC_ID_INDEX 52
#define RTC_ID_SIZE 4
#define SEQUENCE_ID_INDEX 56
#define SEQUENCE_ID_SIZE 4


#endif