#ifndef BF_CONFIG_H
#define BF_CONFIG_H

/*
    all defines refer to the index of the packet
*/
#define DESTINATION_ADDRESS_INDEX 16
#define ETHERNET_DESTINATION_ADDRESS_SIZE 12
#define SOURCE_ADDRESS_INDEX 28
#define ETHERNET_SOURCE_ADDRESS_SIZE 12
#define ETHERNET_TYPE_INDEX 40
#define ETHERNET_TYPE_SIZE 4
#define ETHERNET_PAYLOAD_INDEX 44
#define ETHERNET_CRC_SiZE 8
#define MINIMUM_FRAME_SIZE 144
#define MAXIMUM_FRAME_SIZE 3052


#endif //BF_CONFIG_H